Основы: Часть 2
js-tasks-ru/vue-20240924_danil-x pull request #2
Opened 2024-10-04 19:29 UTC by DanilHvatit

2024-10-04 19:30 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-06 16:10 UTC, ShGKme requested changes

2024-10-06 16:10 UTC, ShGKme commented on 02-basics-2/40-marked-emails/MarkedEmailsApp.js
> +    })
Здесь хорошо подойдёт метод `map`

2024-10-06 16:10 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        <label><input type="radio" @change="calculate(operation)" name="operator" v-model="operation" value="divide"/>➗</label>
И в этой задаче, и в `02-basics-2/50-selected-meetup` - одинаковая проблема.

Приложению в логике его работы лучше отталкиваться в первую очередь именно от его состояния, от данных и их изменения, а не от кликов пользователя, не от событий в DOM. Это одна из основных концепций фреймворка, состояние - источник истины, а DOM - лишь его отображение и интерфейс для изменения.

Если отталкиваться от DOM, то при изменении состояния из другого источника, потребуется изменять компонент, что легко пропустить. (Например, появится ещё оператор, или привязка к query параметрам страницы, или кнопка сброса, или приложение станет компонентом с параметрами и т.д.). За этим нужно следить разработчику. Этой потенциальной проблемы можно избежать, если сразу разрабатывать приложение, отталкиваясь от состояния.

То есть страница, с которой работает пользователь - это лишь интерфейс изменения состояния, но не место описания логики работы приложения.

2024-10-06 16:10 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        <label><input type="radio" @change="calculate(operation)" name="operator" v-model="operation" value="divide"/>➗</label>
Например, в этой задаче значение обновляется только при выборе оператора. Но не обновляется, если поменять число. Обработки изменения операндов нет. В таком стиле потребовалось бы добавить `@change="calculate(operation)"` ещё и элементам ввода чисел.

2024-10-06 16:10 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        <label><input type="radio" @change="calculate(operation)" name="operator" v-model="operation" value="divide"/>➗</label>
Вместо этого нужно описать результат так, чтобы он всегда имел корректное значение от других данных.

2024-10-06 16:10 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +        <button class="button button--secondary" type="button" :disabled="Number(meetupId) === 1" @click="getMet(--meetupId)">Предыдущий</button>
Аналогично в этой задаче пришлось на каждый элемент, в 7 местах добавлять обработку события. Вместо этого нужно отталкиваться от факта изменения `meetupId`. Не важно, как он был изменён.

2024-10-07 18:45 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-08 11:05 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-08 19:20 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-09 13:35 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-13 22:38 UTC, ShGKme requested changes
Требуется явно описывать события в `emit`.

Во многих местах потерялась реактивность. Требуется или использовать объекты напрямую, или создавать переменные через `toRef/toRefs`, либо вычислять через `computed`.

2024-10-13 22:38 UTC, ShGKme commented on 03-components/10-MeetupView/MeetupView.js
> +    const {image, title, agenda, description, organizer, place, date} = props.meetup;
При деструктуризации параметра, как и при деструктуризации любого реактивного объекта - теряется реактивность. Если в компонент придёт новый митап, или в текущем обновится название - обновления в компоненте не будет.

2024-10-13 22:38 UTC, ShGKme commented on 03-components/50-weather-components/components/WeatherCard.js
> +    const isNight = props.city.current.dt < props.city.current.sunrise || props.city.current.dt > props.city.current.sunset
Здесь тоже теряется реактивность. `isNight` только в момент инициализации зависит от пропсов.

2024-10-13 22:38 UTC, ShGKme commented on 03-components/50-weather-components/components/WeatherDetailsList.js
> +    }
Аналогично

2024-10-13 22:38 UTC, ShGKme commented on 03-components/30-removable-emails/EmailList.js
> +        @delete="$emit('deleteItem', index)"
Хотя компонент работает и без явного описания событий в `emits`, настоятельно рекомендуется всегда описыватьсобытия в `emits`:

- Так у компонента есть документация и типизация для разработчиков и различных инструментов
- В случае, если имя события совпадает с DOM событием, оно будет дублироваться

2024-10-14 10:37 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-14 23:23 UTC, ShGKme approved these changes
Принято

2024-10-14 23:23 UTC, ShGKme commented on 04-sfc/10-MeetupView-script-setup/MeetupAgenda.vue
> +import { defineProps } from 'vue'
`define*` - это не настоящая функция, она не существует, как функция, и не выполняется во время работы приложения. Это макрос компиляции - просто указание компилятору на часть кода, которую компилятор будет использовать для генерации кода компонента. Поэтому их не нужно импортировать (в терминале сборки должно быть предупреждение).

2024-10-14 23:23 UTC, ShGKme commented on 04-sfc/20-MeetupCover-style-v-bind/MeetupCover.vue
> +  background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), v-bind('image ? "url("+image+")" : "var(--default-cover)"');
Лучше такие вычисления выносить в `setup`, чтобы оставлять стили максимально простыми от логики и не получать CSS переменных с страшным сгенерированным именем.

2024-10-14 23:23 UTC, ShGKme commented on 04-sfc/30-UiStretch/UiStretch.vue
> +.stretch-container > :deep(picture) {
Хотя `deep` с `>` работает точно также, лучше здесь использовать `:slotted`. Семантически - стилизуется именно содержимое слота.

2024-10-14 23:26 UTC, merged